#!/bin/sh

# This script performs all of the Middlebury-specific initialization steps.

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "Usage: "
  echo "  $0 [-h] [--pantheon-site <site-name>]"
  echo ""
  echo "Any arguments passed to this command will be appended to"
  echo "  lando init --source cwd --recipe pantheon --code none"
  echo ""
  exit 1
fi


# Get to our drupal project root.
cd $(dirname $( dirname -- "$0" ))

# Make sure that we've run `lando init` and the .lando.yml exists.
if [ -f .lando.yml ]; then
  echo ".lando.yml already exists. No need to run 'lando init'"
else
  (lando init --source cwd --recipe pantheon --code none "$@")
fi

./scripts/set-up-site-repo
